---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  releaseName: nginx-ingress
  timeout: 300
  resetValues: false
  wait: true
  forceUpgrade: false
  chart:
    repository: https://charts.helm.sh/stable
    name: nginx-ingress
    version: 1.41.3
  values:
    replicas: 1
    rbac:
      create: true
    controller:
      publishService:
        enabled: true
