# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   name: prometheus
#   namespace: monitoring
#   annotations:
#     fluxcd.io/automated: "false"
#     fluxcd.io/tag.chart-image: semver:~4.0
# spec:
#   releaseName: prometheus
#   chart:
#     repository: https://charts.helm.sh/stable
#     name: prometheus
#     version: 11.12.1
  # values:
  #   image:
  #     repository: bitnami/mongodb
  #     tag: 4.0.13
  #   usePassword: false
  #   persistence:
  #     enabled: false
  #   securityContext:
  #     enabled: true
  #     fsGroup: 0
  #     runAsUser: 0